<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="524" started-at="2021-07-28T16:51:01Z" finished-at="2021-07-28T16:51:02Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="524" started-at="2021-07-28T16:51:01Z" finished-at="2021-07-28T16:51:02Z">
      <class name="org.withoutknown.A">
        <test-method status="PASS" signature="testA1()[pri:0, instance:org.withoutknown.A@c038203]" name="testA1" duration-ms="60" started-at="2021-07-28T22:21:01Z" finished-at="2021-07-28T22:21:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA1 -->
        <test-method status="FAIL" signature="testA2()[pri:0, instance:org.withoutknown.A@c038203]" name="testA2" duration-ms="53" started-at="2021-07-28T22:21:02Z" finished-at="2021-07-28T22:21:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at org.withoutknown.A.testA2(A.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA2 -->
        <test-method status="PASS" signature="testA3()[pri:0, instance:org.withoutknown.A@c038203]" name="testA3" duration-ms="16" started-at="2021-07-28T22:21:02Z" finished-at="2021-07-28T22:21:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA3 -->
      </class> <!-- org.withoutknown.A -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
